#!/bin/bash

# depends: nvm jq

if chezmoi data | jq -e ".meteor" > /dev/null; then
  # leave existing installs in place
  exit 0
fi

export METEOR_NODE_VERSION=v17.0.1
export METEOR_INSTALLER_VERSION=2.5.1

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

! [ -d "$HOME/.nvm/versions/node/$METEOR_NODE_VERSION" ] && nvm install "$METEOR_NODE_VERSION"
if ! [ "$METEOR_INSTALLER_VERSION" = "$(nvm exec --silent "$METEOR_NODE_VERSION" npm list --json -g meteor | jq -r '.dependencies.meteor.version')" ]; then
    nvm exec --silent "$METEOR_NODE_VERSION" npm install -g meteor@"$METEOR_INSTALLER_VERSION"
fi
