#!/bin/bash

# depends: jq

NVM_VERSION="v0.39.0"
export NVM_HOME="$HOME/.nvm"

if chezmoi data | jq -e ".nvm" > /dev/null; then
  # leave existing installs in place
  exit 0
fi

if ! [ -d "$NVM_HOME" ]; then
  git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
fi

if ! [ "$(cd "$NVM_HOME" && git describe --abbrev=0 --tags)" = "$NVM_VERSION" ]; then
  cd "$NVM_HOME"
  git fetch --tags
  git checkout "$NVM_VERSION"
fi
